
import { ChatItem } from "../store.slint";
export component ChatMessageItem inherits Rectangle{
    in property <ChatItem> chat-item;
    HorizontalLayout {
        Rectangle {
            width: 60px;
            height: 65px;
            padding-left: 10px;
            Image {
                source: chat-item.avatar;
                width: 40px;
                height: 40px;
            }
        }
        Rectangle {
            min-width: 70px;
            horizontal-stretch: 1;
            VerticalLayout {
                Rectangle {
                    Text {
                        x: 0px;
                        y: 15px;
                        text:chat-item.name;
                        font-size: 13px;
                    }
                }
                Rectangle {
                    Text {
                        x: 0px;
                        y: 5px;
                        text: chat-item.text;
                        color: rgb(167,167,167);
                        font-size: 12px;
                    }
                }
            }
        }
        Rectangle {
            max-width: 60px;
            VerticalLayout {
                Rectangle {
                    height: 35px;
                    Text {
                        text:chat-item.time;
                        y: 15px;
                        color: rgb(167,167,167);
                        font-size: 12px;
                    }
                }

                Rectangle {
                    height: 30px;
                }
            }
        }
        Rectangle {
            width: 10px;
        }
    }
}