import { MessageInfo } from "message-info.slint";
import { MessageItem } from "../store.slint";
export component MessageList inherits Rectangle{
    in property <[MessageItem]> message-list;
    public function scroll-to-bottom() {
        debug("滚动到最底部");
        flickable.viewport-y =  flickable.height - flickable.viewport-height;
        debug(flickable.height/1px);
        debug(flickable.viewport-height/1px);
        debug(flickable.viewport-y/1px);
        debug("滚动到最底部完成");
    }
    
    flickable := Flickable {
        height: 100%;
         vertical-layout := VerticalLayout{
            height: 100%;
            for message in message-list: MessageInfo {
//                height: self.height;
                message-item: message;
            }
            Rectangle {
                vertical-stretch: 1;
            }
        }
    }
}