import { MessageItem } from "../store.slint";
export component MessageInfo inherits Rectangle{
    in property <MessageItem> message-item;
    property<color> message-background : message-item.send-type=="send" ? rgb(149,236,105) : rgb(255,255,255);
    // background: yellowgreen;
    Rectangle {
        width: 100%;
        min-height: 50px;
        VerticalLayout {
            // padding-top: 5px;
            // padding-left: 10px;
            // padding-bottom: 5px;
            // vertical-stretch: 1;
            //  spacing: 10px;
            // alignment: space-around;
            if message-item.text-type=="text":  HorizontalLayout {
                if message-item.send-type=="receive":Rectangle {
                    width: 20px;
                }
                if message-item.send-type=="receive":Rectangle {
                    width: 50px;
                    height: 35px;
                    Image {
                        source: @image-url("../assets/avatar.jpg");
                        width: 35px;
                        height: 35px;
                    }
                }
                if message-item.send-type=="receive":Path {
                    width: 8px;
                    height: 35px;

                    // 路径数据
                    commands: "M 10 50 L 99 99 L 99 1  Z";
                    // 填充颜色
                    fill:  message-background;
                }
                if message-item.send-type=="receive":Rectangle {
                    background: message-background;
                    border-radius: 5px;
                    horizontal-stretch: 0;
                    width: text.width + 20px;
                    height: text.height + 20px;
                    text:= Text {
                        x: 10px;
                        y: 10px;
                        text:message-item.text;
                        font-size: 13px;
                        color: black;
                        wrap: word-wrap;
                        width: 160px;
                    }
                }
                Rectangle {
                    min-width: 25px;
                    horizontal-stretch: 1;
                }
                if message-item.send-type=="send":Rectangle {
                    background: message-background;
                    border-radius: 5px;
                    horizontal-stretch: 0;
                    width: text-me.width + 20px;
                    height: text-me.height + 20px;
                    text-me:= Text {
                        x: 10px;
                        y: 10px;
                        text:message-item.text;
                        font-size: 13px;
                        color: black;
                        wrap: word-wrap;
                        width: 160px;
                    }
                }
                if message-item.send-type=="send":Path {
                    width: 8px;
                    height: 35px;

                    // 路径数据
                    commands: "M 99 50 L 0 99 L 0 1  Z";
                    // 填充颜色
                    fill:  message-background;
                }
                if message-item.send-type=="send":Rectangle {
                    width: 50px;
                    height: 35px;
                    Image {
                        source: @image-url("../assets/avatar.jpg");
                        width: 35px;
                        height: 35px;
                    }
                }
                if message-item.send-type=="send":Rectangle {
                    width: 20px;
                }
            }
            if message-item.text-type=="system":  HorizontalLayout {
                Rectangle {
                    width: 60px;
                    height: 50px;
                    padding-left: 25px;
                    Image {
                        source: @image-url("../assets/avatar.jpg");
                        width: 36px;
                        height: 36px;
                    }
                }
            }

        }
    }

}