export component SideBar inherits Rectangle{
    background: rgb(46,46,46);
    width: 55px;
    height: 100%;
    border-top-left-radius: 3px;
    border-bottom-left-radius: 3px;
    border-color: rgb(46,46,46);
    border-width: 0px;
    VerticalLayout {
        height: 100%;
      //头像
      Rectangle {
            vertical-stretch: 0;
            height: 80px;
            padding-top: 30px;
            Image {
                source: @image-url("../assets/avatar.jpg");
                width: 40px;
                height: 40px;
            }
        }
      //上工具栏
      Rectangle {
            vertical-stretch: 1;
            min-height: 260px;
            background: transparent;
            Rectangle {
                height: 100%;
                vertical-stretch: 1;
                VerticalLayout {
                    alignment: start;
                    Rectangle {
                        height: 40px;
                        Image {
                            source: @image-url("../assets/icon/home.svg");
                            width: 25px;
                            height: 25px;
                        }
                    }

                    Rectangle {
                        height: 40px;
                        Image {
                            source: @image-url("../assets/icon/contact.svg");
                            width: 25px;
                            height: 25px;
                        }
                    }

                    Rectangle {
                        height: 40px;
                        Image {
                            source: @image-url("../assets/icon/collect.svg");
                            width: 23px;
                            height: 25px;
                        }
                    }

                    Rectangle {
                        height: 40px;
                        Image {
                            source: @image-url("../assets/icon/folder.svg");
                            width: 23px;
                            height: 25px;
                        }
                    }

                    Rectangle {
                        height: 40px;
                        Image {
                            source: @image-url("../assets/icon/circle.svg");
                            width: 21px;
                            height: 23px;
                        }
                    }

                    Rectangle {
                        height: 40px;
                        Image {
                            source: @image-url("../assets/icon/video.svg");
                            width: 25px;
                            height: 25px;
                        }
                    }
                }
            }
        }
      //下工具栏
      Rectangle {
            vertical-stretch: 0;
            height: 130px;
            background: transparent;
            VerticalLayout {
                alignment: end;
                Rectangle {
                    height: 40px;
                    Image {
                        source: @image-url("../assets/icon/mini.svg");
                        width: 23px;
                        height: 23px;
                    }
                }

                Rectangle {
                    height: 40px;
                    Image {
                        source: @image-url("../assets/icon/phone.svg");
                        width: 25px;
                        height: 25px;
                    }
                }

                Rectangle {
                    height: 40px;
                    Image {
                        source: @image-url("../assets/icon/setting.svg");
                        width: 25px;
                        height: 25px;
                    }
                }

                Rectangle {
                    height: 20px;
                }
            }
        }
    }

 } 