import { ChatMessageList } from "../component/chat-message-list.slint";
import { ChatBox } from "../component/chat-box.slint";
import { Store,MessageItem,AppGlobal } from "../store.slint";
export component Home inherits Rectangle{ 
    horizontal-stretch: 1;
    public function scroll-to-bottom() {
        chat-box.scroll-to-bottom();
    }
    HorizontalLayout {
        alignment: stretch;
        //消息列表
        ChatMessageList {
            background: rgb(247,247,247);
            width: 200px;
            height: 100%;
            border-width: 1px;
            border-color: rgb(214,214,214);
            chat-list: Store.chat-items;
        }
       chat-box:= ChatBox {
            message-list: Store.message-items;
            border-top-right-radius: 3px;
            border-bottom-right-radius: 3px;
            min-width: 444px;
            height: 100%;
            horizontal-stretch: 1;
            background: rgb(245,245,245);
        }
    }
}