import { BorderlessWindow } from "component/borderless-window.slint";



export component Main inherits BorderlessWindow {
    // 设置窗口标题
    title: "Me Chat";
    // 设置窗口大小
    min-width: 700px;
    min-height: 500px;
    callback close-window();
    callback minimized-window(bool);
    callback maximized-window(bool);
    callback move-window(length, length);
    callback mouse-down(int, int);
    callback mouse-move(int, int);

    on-close-window() => {
        close-window();
    }

    on-minimized-window(enable) => {
        minimized-window(enable);
    }

    on-maximized-window(enable) => {
        maximized-window(enable);
    }

    on-move-window(offset-x, offset-y) => {
        move-window(offset-x, offset-y);
    }

    HorizontalLayout {
        //工具栏
        Rectangle {
            background: rgb(46,46,46);
            width: 55px;
            height: 100%;
            border-top-left-radius: 3px;
            border-bottom-left-radius: 3px;
            border-color: rgb(46,46,46);
            border-width: 0px;
            TouchArea {
                pointer-event(ev) => {
                    root.process-drag-event(0, ev, self.mouse-x, self.mouse-y);
                }
            }
            VerticalLayout{
              height: 100%;
              //头像
              Rectangle{
                vertical-stretch: 0;
                height: 100px;
                padding-top: 30px;
                Image {
                  source: @image-url("assets/avatar.jpg");
                  width: 40px;
                  height: 40px;
                }
              }
              //上工具栏
              Rectangle{
                vertical-stretch: 1;
                min-height: 260px;
                background: transparent;
                Rectangle {
                  height: 100%;
                  vertical-stretch: 1;
                  VerticalLayout{
                    alignment: start;
                    Rectangle{
                      height: 40px;
                      Image {
                        source: @image-url("assets/icon/home.svg");
                        width: 25px;
                        height: 25px;
                      }
                    }
                    Rectangle{
                      height: 40px;
                      Image {
                        source: @image-url("assets/icon/contact.svg");
                        width: 25px;
                        height: 25px;
                      }
                    }
                    Rectangle{
                      height: 40px;
                      Image {
                        source: @image-url("assets/icon/collect.svg");
                        width: 25px;
                        height: 25px;
                      }
                    }
                    Rectangle{
                      height: 40px;
                      Image {
                        source: @image-url("assets/icon/folder.svg");
                        width: 25px;
                        height: 25px;
                      }
                    }
                    Rectangle{
                      height: 40px;
                      Image {
                        source: @image-url("assets/icon/circle.svg");
                        width: 25px;
                        height: 25px;
                      }
                    }
                    Rectangle{
                      height: 40px;
                      Image {
                        source: @image-url("assets/icon/video.svg");
                        width: 25px;
                        height: 25px;
                      }
                    }
                  }
                }
              }
              //下工具栏
              Rectangle{
                vertical-stretch: 0;
                height: 130px;
                background: transparent;
                VerticalLayout{
                alignment: end;
                Rectangle{
                  height: 40px;
                  Image {
                    source: @image-url("assets/icon/mini.svg");
                    width: 25px;
                    height: 25px;
                  }
                }
                Rectangle{
                  height: 40px;
                  Image {
                    source: @image-url("assets/icon/phone.svg");
                    width: 28px;
                    height: 28px;
                  }
                }
                Rectangle{
                  height: 40px;
                  Image {
                    source: @image-url("assets/icon/setting.svg");
                    width: 25px;
                    height: 25px;
                  }
                }
                Rectangle{
                  height: 20px;
                }
              }
            }
            }
        }
        //消息列表
        Rectangle {
          background: rgb(247,247,247);
          width: 200px;
          height: 100%;
          border-width: 1px;
          border-color: rgb(214,214,214);
          VerticalLayout{
            Rectangle {
              height: 28px;
              background: transparent;
              TouchArea {
                pointer-event(ev) => {
                    root.process-drag-event(0, ev, self.mouse-x, self.mouse-y);
                }
              }
            }
            Rectangle {
              background: transparent;
              height: 40px;
              HorizontalLayout {
                alignment: space-around;
                //搜索框
                Rectangle {
                  width: 130px;
                  height: 30px;
                  horizontal-stretch: 1;
                  background: rgb(226,226,226);
                  border-radius: 5px;
                  padding: 5px;
                  VerticalLayout {
                    alignment: start;
                    padding: 5px;
                    Image {
                      horizontal-stretch: 0;
                      source: @image-url("assets/icon/search.svg");
                      width: 20px;
                      height: 20px;
                    }
                  }
                }
                //加号框
                Rectangle {
                  width: 30px;
                  height: 30px;
                  background: rgb(226,226,226);
                  border-radius: 5px;
                  padding: 5px;
                  Image {
                    source: @image-url("assets/icon/more.svg");
                    width: 20px;
                    height: 20px;
                  }
                }
              }
            }
            Rectangle {
              horizontal-stretch: 1;
              background: rgb(230,230,230);
              VerticalLayout {
                alignment: start;
                Rectangle {
                  height: 65px;
                  HorizontalLayout {
                    Rectangle {
                      width: 40px;
                      height: 40px;
                      Image {
                        source: @image-url("assets/avatar.jpg");
                        width: 40px;
                        height: 40px;
                      }
                    }
                    Rectangle {
                      min-width: 100px;
                      VerticalLayout {
                        Rectangle {
                          Text {
                            text: "文件传输助手";
                          }
                          }
                          Rectangle {
                            Text {
                              text: "aabb";
                            }
                            }
                      }
                    }
                    Rectangle {
                      max-width: 60px;
                      Text {
                        text: "昨天";
                      }
                    }
                  }
                }
              }
            }
          }
        }
        //聊天框
        Rectangle {
          background: rgb(245,245,245);
          border-top-right-radius: 3px;
          border-bottom-right-radius: 3px;
          min-width: 444px;
          height: 100%;
          VerticalLayout{
            Rectangle {
              horizontal-stretch: 0;
              height: 28px;
              background: transparent;
              TouchArea {
                pointer-event(ev) => {
                    root.process-drag-event(0, ev, self.mouse-x, self.mouse-y);
                }
              }
              HorizontalLayout {
                alignment:end;
                //最小化按钮
                Rectangle {
                    Rectangle {
                        border-radius: 3px;
                        width: 24px;
                        height: 24px;
                        background: transparent;
                        touch-minize := TouchArea {
                            clicked => { root.on-minimized-window(true) }
                        }
                        Text {
                            color: rgba(79,79,79,0.8);
                            text: "-";
                            font-size: 24px;
                        }
                    }
                    width: 30px;
                }
                //最大化按钮
                Rectangle {
                    Rectangle {
                        border-radius: 3px;
                        width: 24px;
                        height: 24px;
                        background: transparent;
                        touch-maximized := TouchArea {
                            clicked => {
                                root.is-maximized = !root.is-maximized;
                                root.on-maximized-window(root.is-maximized);
                            }
                        }
                        Text {
                            color: rgba(79,79,79,0.8);
                            text: root.is-maximized?"❐":"□";
                            font-size: 24px;
                        }
                    }
                    width: 30px;
                }
                //关闭按钮
                Rectangle {
                  Rectangle {
                      border-radius: 3px;
                      y: 5px;
                      width: 24px;
                      height: 24px;
                      background: transparent;
                      touch-close := TouchArea {
                        clicked => { root.on-close-window() }
                    }
                    Text {
                        color: rgba(79,79,79,0.8);
                        text: "×";
                        font-size: 24px;
                    }
                  }
                  width: 30px;
              }
              }
            }
            Rectangle {
              horizontal-stretch: 1;
              background: rgb(245,245,245);

            }
          }
        }
      }
    
}
