import { BorderlessWindow } from "component/base/borderless-window.slint";
import { SideBar } from "component/base/side-bar.slint";
import { Home } from "page/home.slint";
import { TabIndex, Store,AppGlobal } from "./store.slint";

export struct FriendInfo {
    id: int,
    username: string,
}

export component Main inherits BorderlessWindow {
    // 设置窗口标题
    title: "Me Chat";
    icon: @image-url("assets/icon.png");
    // 设置窗口大小
    min-width: 700px;
    min-height: 500px;
    public function scroll-to-bottom() {
        home-page.scroll-to-bottom();
    }
    HorizontalLayout {
        alignment: stretch;
        //工具栏
        side-bar := SideBar {
            icon-items:[
                {item: {id: TabIndex.Chat, text: "聊天", icon: @image-url("assets/icon/chat.svg")}},
                {item: {id: TabIndex.Collect, text: "联系人", icon: @image-url("assets/icon/contact.svg")}},
                {item: {id: TabIndex.Collect, text: "收藏", icon: @image-url("assets/icon/collect.svg")}},
                {item: {id: TabIndex.File, text: "文件", icon: @image-url("assets/icon/folder.svg")}},
                {item: {id: TabIndex.Circle, text: "朋友圈", icon: @image-url("assets/icon/circle.svg")}},
                {item: {id: TabIndex.Video, text: "视频号", icon: @image-url("assets/icon/video.svg")}},
            ];
            setting-items:[
                {item: {id: TabIndex.Mini, text: "小程序", icon: @image-url("assets/icon/mini.svg")}},
                {item: {id: TabIndex.Phone, text: "电话", icon: @image-url("assets/icon/phone.svg")}},
                {item: {id: TabIndex.Setting, text: "设置", icon: @image-url("assets/icon/setting.svg")}},
            ];
            TouchArea {
                pointer-event(ev) => {
                    root.process-drag-event(0, ev, self.mouse-x, self.mouse-y);
                }
            }
        }
        //聊天框
        home-page :=  Home {
        }
    }
}
