import { BorderlessWindow } from "component/borderless-window.slint";
import { SideBar } from "component/side_bar.slint";
import { Chat } from "page/chat.slint";

export component Main inherits BorderlessWindow {
    // 设置窗口标题
    title: "Me Chat";
    icon: @image-url("assets/icon.png");
    // 设置窗口大小
    min-width: 700px;
    min-height: 500px;
    in property <string> completion;
    callback send-message(string, string);

    callback close-window();
    callback minimized-window(bool);
    callback maximized-window(bool);
    callback move-window(length, length);
    callback mouse-down(int, int);
    callback mouse-move(int, int);
    on-close-window() => {
        close-window();
    }
    on-minimized-window(enable) => {
        minimized-window(enable);
    }
    on-maximized-window(enable) => {
        maximized-window(enable);
    }
    on-move-window(offset-x, offset-y) => {
        move-window(offset-x, offset-y);
    }
    HorizontalLayout {
        alignment: stretch;
        //工具栏
        side-bar := SideBar {
            TouchArea {
                pointer-event(ev) => {
                    root.process-drag-event(0, ev, self.mouse-x, self.mouse-y);
                }
            }
        }
        chat-page :=  Chat {
            process-drag-event(type,ev,x,y) => {
                root.process-drag-event(type, ev, x, y);
            }
            minimized-window(enable) => {
                root.minimized-window(enable);
            }
            maximized-window(enable) => {
                root.maximized-window(enable);
            }
            close-window() => {
                root.close-window();
            }
        }
    }
}
