export enum TabIndex {
    None,//无
    Chat,//聊天
    Contacts,//联系人
    Collect,//收藏
    File,//文件
    Circle,//朋友圈
    Video,//视频号
    Mini,//小程序
    Phone,//电话
    Setting,//设置
}

//图标列表
export struct IconItem {
    id:TabIndex, //唯一标识
    text: string,//描述文本
    icon: image,//图标
}
//左侧聊天列表
export struct ChatItem {
    id: int,
    name: string,
    avatar: image,
    text: string,
    text-type: string,
    time: string,
}

export struct MessageItem {
    text: string,
    avatar: image,
    text-type: string,
    send-type: string,
    time: string,
}
//用户信息
export struct UserInfo {
    id: int,
    name: string,//用户名
    avatar: image,//用户头像
    signature: string,//用户签名
    background: image,//用户背景
    phone: string,//用户手机号
    email: string,//用户邮箱
}

export struct FriendInfo {
    id: int,
    username: string,
}

//全局状态
export global Store {
    //用户信息
    in-out property <UserInfo> user-info;

    in-out property <TabIndex> current-tab-index: TabIndex.Chat;//当前选中的tab
    in-out property <[ChatItem]> chat-items;//消息列表
    in-out property <[MessageItem]> message-items;//聊天消息列表
    in-out property <int> current-chat;
}
//全局函数
export global AppGlobal {
    callback chat-selected(int);
    callback send-message(string);
    callback close-window();
    callback minimized-window(bool);
    callback maximized-window(bool);
    callback move-window(length, length);
    callback mouse-down(int, int);
    callback mouse-move(int, int);
}

export global Images {
    in-out property <image> tensor: @image-url("assets/tensor.jpg");
}